name: Criar APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - name: Instalar Buildozer
        run: |
          sudo apt update
          sudo apt install -y libffi-dev libssl-dev libbz2-dev
          pip install --upgrade pip
          pip install cython==0.29.33 buildozer
      - name: Gerar APK
        run: |
          buildozer android debug
      - name: Salvar APK
        uses: actions/upload-artifact@v4
        with:
          name: meu-apk
          path: bin/*.apk
      
